<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-BlackPuma075/blob/main/Ago11_12_Tarea1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python lists**

In [3]:
import numpy as np
np.__version__

'1.23.5'

Create a list of integers

In [4]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
type(L[0])

int

List of strings

In [7]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
type(L2[0])

str

Homogeneous lists

In [11]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

**Fixed-type arrays**

In [12]:
import array as arr
L = list(range(10))
A = arr.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Creating arrays from python lists**

In [13]:
np.array([0,1,2,3,4])

array([0, 1, 2, 3, 4])

For explicitly fix the data type:

In [15]:
np.array([1,2,3,4], dtype = 'float')

array([1., 2., 3., 4.])

Multidimensional arrays

In [16]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

**Creating arrays from scratch**

In [17]:
#Create a lentgh-10 array filled with zeros
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype = 'float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
#Create 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [27]:
#Create an array filled with a sequence stepping by 2
np.arange(0, 20, 2)
#np.arange?

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)
#np.linspace?

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))
#np.random.random?

array([[0.61473964, 0.42129018, 0.8624049 ],
       [0.13872924, 0.58287964, 0.37023536],
       [0.93469297, 0.92204272, 0.01617196]])

In [34]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))
#np.random.normal?

array([[ 0.25577672,  1.34550299, -1.44602551],
       [-0.04756352, -3.16763668,  0.36195222],
       [-0.16178097, -0.67030148,  1.06275062]])

In [43]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))
np.random.randint?

In [37]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
#np.empty?
np.empty((2,2), float)

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

**Numpy arrays atributes**

In [46]:
np.random.seed(0) #seed for reproducibility

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

In [49]:
#Useful array attributes number of dimensions, size of each dimension, tot size
print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)
print('dtype:', x3.dtype)
print('itemsize:', x3.itemsize, 'bytes') #size of each element
print('nbytes:', x3.nbytes, 'bytes') #size of total elements

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


**Array indexing**

In [52]:
x1

array([5, 0, 3, 3, 7, 9])

In [53]:
x1[0]

5

In [54]:
x1[-1] #from the end of the array

9

In [55]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [57]:
x2[0,0] = 10 #modify an element
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

**Array slicing**

In [59]:
#x[start:stop:step]

In [60]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
x[:5]

array([0, 1, 2, 3, 4])

In [62]:
x[5:]

array([5, 6, 7, 8, 9])

In [63]:
x[3:6]

array([3, 4, 5])

In [64]:
x[::2]

array([0, 2, 4, 6, 8])

In [65]:
x[1::2]

array([1, 3, 5, 7, 9])

In [66]:
x[::-1] #all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [67]:
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [69]:
x2[:3,:2] #two rows, three columns

array([[10,  5],
       [ 7,  6],
       [ 1,  6]])

In [70]:
x2[:3, ::2]

array([[10,  2],
       [ 7,  8],
       [ 1,  7]])

In [71]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 10]])

In [72]:
print(x2[:,0]) #first column
print(x2[0,:]) #first row

[10  7  1]
[10  5  2  4]


In [73]:
x2_subarray = x2[:2,:2] #its a view of the array, not a copy!
print(x2_subarray)

[[10  5]
 [ 7  6]]


In [74]:
x2_subarray[0,0] = 99 #it also change the original array!!!!
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

**Creating a copy**

In [75]:
x2_subcopy = x2[:2,:2].copy()
x2_subcopy

array([[99,  5],
       [ 7,  6]])

**Reshaping of arrays**

In [77]:
grid = np.arange(1,10).reshape(3,3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [80]:
x.reshape(3,1)

array([[1],
       [2],
       [3]])

In [81]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

**Concatenation of arrays**

In [83]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [84]:
z = [9,9,9]
np.concatenate([x,y,z])

array([1, 2, 3, 3, 2, 1, 9, 9, 9])

In [86]:
grid1 = ([1,2,3],
         [3,2,1])
np.concatenate([grid1,grid1]) #first axis

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3],
       [3, 2, 1]])

In [87]:
np.concatenate([grid1,grid1], axis=1) #second axis

array([[1, 2, 3, 1, 2, 3],
       [3, 2, 1, 3, 2, 1]])

In [88]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [89]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [90]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) #given the split points (3,5)
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [91]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [93]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


**Computation of NumPy arrays**