<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-BlackPuma075/blob/main/Ago11-12/Mi_primer_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hola mundo')

Hola mundo


In [ ]:
lista1 = [2, "2",'dos', 2.0]
lista2 = ['4', 'cuatro']

In [ ]:
del lista1[2]

In [ ]:
lista1

[2, '2', 2.0]

In [ ]:
lista1.insert(2, 'tres')

In [ ]:
lista1

[2, '2', 'tres', 2.0]

In [ ]:
lista3 = [lista1, lista2]

In [ ]:
lista3

[[2, '2', 'tres', 2.0], ['4', 'cuatro']]

In [ ]:
for i in lista1:
  print(i)

2
2
tres
2.0


In [ ]:
for i in range(len(lista1)):
  print(i,lista1[i])

0 2
1 2
2 tres
3 2.0


In [ ]:
for i,item in enumerate(lista1):
  print(i,item)

0 2
1 2
2 tres
3 2.0


In [ ]:
type(lista1)

list

In [ ]:
import array as arr

In [ ]:
arreglo = arr.array('i',[1,2,3])

In [ ]:
arreglo

array('i', [1, 2, 3])

In [ ]:
arreglo1 = arr.array('f',[1,2,3])

In [ ]:
2*arreglo1

array('f', [1.0, 2.0, 3.0, 1.0, 2.0, 3.0])

In [ ]:
import numpy as np

In [ ]:
nparr1 = np.array([1,2,3])

In [ ]:
nparr1

array([1, 2, 3])

In [ ]:
type(nparr1)

numpy.ndarray

In [ ]:
2*nparr1

array([2, 4, 6])

In [ ]:
nparr2 = np.array([1,2,3])

In [ ]:
nparr2*nparr1

array([1, 4, 9])

In [ ]:
np.dot(nparr1,nparr2)

14

In [ ]:
nparr1/nparr2

array([1., 1., 1.])